// In the file db.json, the texts were generated by the Chat GPT: https://chat.openai.com/chat
// I based my structure on this API: https://api.sampleapis.com/coffee/hot

const jsonServer = require('json-server');
const server = jsonServer.create();
const router = jsonServer.router('db.json');
const middlewares = jsonServer.defaults();
const PORT = process.env.PORT || 3000;

server.use(middlewares);
server.use(router);

server.listen(PORT);
